spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hypro_wash
    username: postgresql
    password: lereve
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

